apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-academy-frontend.fullname" . }}
  labels:
    app: {{ include "devops-academy-frontend.name" . }}
    chart: {{ include "devops-academy-frontend.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "devops-academy-frontend.name" . }}
    release: {{ .Release.Name }}
